language: generic
sudo: required 
services: 
  - docker 

before_install:
  - docker build -t gjohncarter/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gjohncarter/react-test npm test 

after_success:
  - docker build -t gjohncarter/fibo-client ./client
  - docker build -t gjohncarter/fibo-nginx ./nginx
  - docker build -t gjohncarter/fibo-server ./server
  - docker build -t gjohncarter/fibo-worker ./worker
  # Log in to Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take the images and push them to dockerhub
  - docker push gjohncarter/fibo-client
  - docker push gjohncarter/fibo-nginx
  - docker push gjohncarter/fibo-server
  - docker push gjohncarter/fibo-worker

