sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gjohncarter/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gjohncarter/react-test npm test

after_success:
  - docker build -t gjohncarter/multi-client ./client
  - docker build -t gjohncarter/multi-nginx ./nginx
  - docker build -t gjohncarter/multi-server ./server
  - docker build -t gjohncarter/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push gjohncarter/multi-client
  - docker push gjohncarter/multi-nginx
  - docker push gjohncarter/multi-server
  - docker push gjohncarter/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi_container_docker_travis_awseb_deploy'
  env: 'dev-ecs-env'
  bucket_name: 'elasticbeanstalk-us-west-2-968507404816'
  bucket_path: '_docker_react_travisci_awseb_app'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
