language: generic
sudo: required 
services: 
  - docker 

before_install:
  - docker build -t gjohncarter/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gjohncarter/react-test npm test 

after_success:
  - docker build -t gjohncarter/fibo-client ./client
  - docker build -t gjohncarter/fibo-nginx ./nginx
  - docker build -t gjohncarter/fibo-server ./server
  - docker build -t gjohncarter/fibo-worker ./worker

